name: getx
description: "A powerful and updated version of the GetX package for Flutter, offering enhanced state management, routing, and dependency injection. 
  This version includes new features, performance improvements, and better compatibility with the latest Flutter updates."
 
version: 0.0.1
homepage: "https://github.com/SwanFlutter/getx"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  intl: ^0.20.2
  shamsi_date: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


